plugins {
    id 'java'
    id 'application'
    id 'com.github.johnrengelman.shadow' version '8.1.1'
}

group = project.group
archivesBaseName = project.name
version = project.version
mainClassName = project.main

repositories {
    mavenCentral()
}

dependencies {
    implementation "com.formdev:flatlaf:${project.flatlaf}"
    implementation "com.fasterxml.jackson.core:jackson-databind:${project.jackson}"
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 8
}

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

processResources {
    inputs.properties 'version': project.version

    filesMatching('version.json') {
        expand 'version': project.version
    }
}


jar {
    manifest {
        attributes["Implementation-Title"] = archivesBaseName
        attributes["Implementation-Version"] = version
        attributes["Main-Class"] = mainClassName
    }
}
shadowJar {
    manifest {
        attributes(
                'Implementation-Title': archivesBaseName,
                'Implementation-Version': version,
                'Main-Class': mainClassName
        )
    }
    mergeServiceFiles()
}
build.dependsOn shadowJar